name: chat_app
description: Chat App that allows users to send and receive messages and photos.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts:
  cupertino_icons: ^1.0.0
  firebase_auth: ^0.18.0+1
  cloud_firestore: ^0.14.0+2
  firebase_core: ^0.5.0
  shared_preferences: ^0.5.12
  shared_preferences_windows: ^0.0.1+1
  google_sign_in:
  fluttertoast:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/images/